/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main;

import com.formdev.flatlaf.intellijthemes.FlatArcDarkIJTheme;
import com.formdev.flatlaf.intellijthemes.FlatArcIJTheme;
import com.formdev.flatlaf.intellijthemes.FlatCarbonIJTheme;
import java.awt.BorderLayout;
import javax.swing.JPanel;
import javax.swing.UIManager;
import main.views.*;

/**
 *
 * @author jyane
 */
public class UI_UX extends javax.swing.JFrame {

    private void initStyles(){
        VitaLink_Name.putClientProperty( "FlatLaf.styleClass", "h0" );
        VitaLink_Name1.putClientProperty( "FlatLaf.styleClass", "h1" );
    }

    public UI_UX() {
        initComponents();
        initStyles();
        InitContent();
    }

    private void ShowJPanel(JPanel p){
        p.setSize(1540, 960);
        p.setLocation(0,0);
        content.removeAll();
        content.add(p,BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }

    private void InitContent(){
        ShowJPanel(new Principal());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DashBoard = new javax.swing.JPanel();
        LeftMenu = new javax.swing.JPanel();
        VitaLink_Name1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        ingresarPacienteButton = new javax.swing.JButton();
        PrincipalButton = new javax.swing.JButton();
        HistorialMedicoButtonButton = new javax.swing.JButton();
        AsignarDiagnosticoButton = new javax.swing.JButton();
        CrearConsultaButton1 = new javax.swing.JButton();
        Header = new javax.swing.JPanel();
        VitaLink_Name = new javax.swing.JLabel();
        FechHeader = new javax.swing.JLabel();
        content = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        DashBoard.setAlignmentX(0.0F);
        DashBoard.setAlignmentY(0.0F);
        DashBoard.setMinimumSize(new java.awt.Dimension(0, 0));
        DashBoard.setPreferredSize(new java.awt.Dimension(1920, 1080));

        LeftMenu.setBackground(new java.awt.Color(61, 97, 133));
        LeftMenu.setPreferredSize(new java.awt.Dimension(384, 1080));
        LeftMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        VitaLink_Name1.setText("VitaLink");
        LeftMenu.add(VitaLink_Name1, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 17, -1, -1));
        LeftMenu.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 51, 384, 10));

        ingresarPacienteButton.setText("Ingresar Paciente");
        ingresarPacienteButton.setBorder(null);
        ingresarPacienteButton.setBorderPainted(false);
        ingresarPacienteButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ingresarPacienteButton.setPreferredSize(new java.awt.Dimension(384, 65));
        ingresarPacienteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresarPacienteButtonActionPerformed(evt);
            }
        });
        LeftMenu.add(ingresarPacienteButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 148, -1, 75));

        PrincipalButton.setText("Principal");
        PrincipalButton.setBorder(null);
        PrincipalButton.setBorderPainted(false);
        PrincipalButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PrincipalButton.setPreferredSize(new java.awt.Dimension(384, 65));
        PrincipalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrincipalButtonActionPerformed(evt);
            }
        });
        LeftMenu.add(PrincipalButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 67, -1, 75));

        HistorialMedicoButtonButton.setText("Historial Médico del Paciente");
        HistorialMedicoButtonButton.setBorder(null);
        HistorialMedicoButtonButton.setBorderPainted(false);
        HistorialMedicoButtonButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        HistorialMedicoButtonButton.setPreferredSize(new java.awt.Dimension(384, 65));
        HistorialMedicoButtonButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HistorialMedicoButtonButtonActionPerformed(evt);
            }
        });
        LeftMenu.add(HistorialMedicoButtonButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 229, -1, 75));

        AsignarDiagnosticoButton.setText("Asignar Diagnóstico");
        AsignarDiagnosticoButton.setBorder(null);
        AsignarDiagnosticoButton.setBorderPainted(false);
        AsignarDiagnosticoButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AsignarDiagnosticoButton.setPreferredSize(new java.awt.Dimension(384, 65));
        AsignarDiagnosticoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AsignarDiagnosticoButtonActionPerformed(evt);
            }
        });
        LeftMenu.add(AsignarDiagnosticoButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, -1, 75));

        CrearConsultaButton1.setText("Crear Consulta");
        CrearConsultaButton1.setBorder(null);
        CrearConsultaButton1.setBorderPainted(false);
        CrearConsultaButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CrearConsultaButton1.setPreferredSize(new java.awt.Dimension(384, 65));
        CrearConsultaButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearConsultaButton1ActionPerformed(evt);
            }
        });
        LeftMenu.add(CrearConsultaButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, -1, 75));

        Header.setBackground(new java.awt.Color(50, 119, 189));
        Header.setPreferredSize(new java.awt.Dimension(1536, 120));

        VitaLink_Name.setText("VitaLink");

        FechHeader.setText("Hoy es {dayname} {day} de {month} de {year}");

        javax.swing.GroupLayout HeaderLayout = new javax.swing.GroupLayout(Header);
        Header.setLayout(HeaderLayout);
        HeaderLayout.setHorizontalGroup(
                HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(HeaderLayout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addGroup(HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(VitaLink_Name)
                                        .addComponent(FechHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(1309, Short.MAX_VALUE))
        );
        HeaderLayout.setVerticalGroup(
                HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(HeaderLayout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(VitaLink_Name)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                                .addComponent(FechHeader)
                                .addGap(32, 32, 32))
        );

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
                contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 1540, Short.MAX_VALUE)
        );
        contentLayout.setVerticalGroup(
                contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 960, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout DashBoardLayout = new javax.swing.GroupLayout(DashBoard);
        DashBoard.setLayout(DashBoardLayout);
        DashBoardLayout.setHorizontalGroup(
                DashBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(DashBoardLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(LeftMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(DashBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(Header, javax.swing.GroupLayout.PREFERRED_SIZE, 1636, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(content, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        DashBoardLayout.setVerticalGroup(
                DashBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(DashBoardLayout.createSequentialGroup()
                                .addComponent(Header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(content, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(LeftMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(DashBoard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(DashBoard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
        );

        DashBoard.getAccessibleContext().setAccessibleName("");
        DashBoard.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PrincipalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrincipalButtonActionPerformed
        // TODO add your handling code here:
        ShowJPanel(new Principal());
    }//GEN-LAST:event_PrincipalButtonActionPerformed

    private void HistorialMedicoButtonButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HistorialMedicoButtonButtonActionPerformed
        // TODO add your handling code here:
        ShowJPanel(new Buscar_Paciente());
    }//GEN-LAST:event_HistorialMedicoButtonButtonActionPerformed

    private void AsignarDiagnosticoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AsignarDiagnosticoButtonActionPerformed
        // TODO add your handling code here:
        ShowJPanel(new Consulta());
    }//GEN-LAST:event_AsignarDiagnosticoButtonActionPerformed

    private void ingresarPacienteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresarPacienteButtonActionPerformed
        // TODO add your handling code here:
        ShowJPanel(new Ingresar_paciente());
    }//GEN-LAST:event_ingresarPacienteButtonActionPerformed

    private void CrearConsultaButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearConsultaButton1ActionPerformed
        // TODO add your handling code here:
        ShowJPanel(new Crear_Consulta());
    }//GEN-LAST:event_CrearConsultaButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        FlatCarbonIJTheme.setup();
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UI_UX().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AsignarDiagnosticoButton;
    private javax.swing.JButton CrearConsultaButton1;
    private javax.swing.JPanel DashBoard;
    private javax.swing.JLabel FechHeader;
    private javax.swing.JPanel Header;
    private javax.swing.JButton HistorialMedicoButtonButton;
    private javax.swing.JPanel LeftMenu;
    private javax.swing.JButton PrincipalButton;
    private javax.swing.JLabel VitaLink_Name;
    private javax.swing.JLabel VitaLink_Name1;
    private javax.swing.JPanel content;
    private javax.swing.JButton ingresarPacienteButton;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables

}
