/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package main.views;

import Consultas.Diagnostico;
import Consultas.Enfermedad;
import HistorialMedico.BPlusTree;
import Pacientes.Paciente;
import java.awt.BorderLayout;
import java.awt.Color;
import javax.swing.JPanel;
import com.formdev.flatlaf.intellijthemes.FlatArcDarkIJTheme;
import java.awt.BorderLayout;
import java.io.IOException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JPanel;
import javax.swing.UIManager;
import main.FileManager;
import main.views.*;

/**
 *
 * @author PC
 */
public class FormularioDiagnostico extends javax.swing.JPanel {

    DefaultListModel Enferme = new DefaultListModel();
    DefaultListModel Medic = new DefaultListModel();
    DefaultListModel Fechas = new DefaultListModel();
    ArrayList<Enfermedad> Enfers = new ArrayList();
    ArrayList<String> Medics = new ArrayList();
    static ArrayList<Paciente> array;

    /**
     * Creates new form Ingresar_paciente
     */
    public FormularioDiagnostico(Paciente paciente) {
        initComponents();
        MostrarDatos(paciente);
        Enfermedades.setModel(Enferme);
        Receta.setModel(Medic);
        FechasMostrarLista(paciente.getConsultas(), Fechas);
        FechasList.setModel(Fechas);
        array = new ArrayList();
        array.add(paciente);
        InitStyles();
    }

    private void FechasMostrarLista(ArrayList<Consultas.Consulta> e, DefaultListModel modelo) {
        modelo.removeAllElements();
        for (int i = 0; i < e.size(); i++) {
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            String str = sdf.format(e.get(i).getFechaConsulta());
            modelo.addElement(str);
        }
    }

    public void MostrarDatos(Paciente paciente) {
        jLabel1.setText(paciente.getNombre());

    }

    private void InitStyles() {
        Color colorBase = new Color(50, 119, 189);
        Display_FechaConsulta.putClientProperty("Flatlaf.styleClass", "default");
        Display_FechaConsulta.setForeground(Color.black);
        Display_Paciente.putClientProperty("Flatlaf.styleClass", "default");
        Display_Paciente.setForeground(Color.black);
        Display_Doctor.putClientProperty("Flatlaf.styleClass", "default");
        Display_Doctor.setForeground(Color.black);
        Display_Especialidad.putClientProperty("Flatlaf.styleClass", "default");
        Display_Especialidad.setForeground(Color.black);
        Display_Diagnostico.putClientProperty("Flatlaf.styleClass", "default");
        Display_Diagnostico.setForeground(Color.black);
        Display_Receta.putClientProperty("Flatlaf.styleClass", "default");
        Display_Receta.setForeground(Color.black);
        Cronico.putClientProperty("Flatlaf.styleClass", "default");
        Cronico.setForeground(Color.black);
        jLabel1.setForeground(Color.black);
        ShowDoctor.setForeground(Color.black);
        ShowEspecialidad.setForeground(Color.black);

    }

    public void EnferAgregarAct(Enfermedad enfer, DefaultListModel modelo) {
        Enfers.add(enfer);
        if (enfer.isCronico()) {
            modelo.addElement(enfer.getNombre() + " - es crónico.");
        } else {
            modelo.addElement(enfer.getNombre());
        }
    }

    public void EnferEliminarAct(int index, DefaultListModel modelo) {
        Enfers.remove(index);
        modelo.remove(index);
    }

    public void MedAgregarAct(String str, DefaultListModel modelo) {
        Medics.add(str);
        modelo.addElement(str);
    }

    public void MedEliminarAct(int index, DefaultListModel modelo) {
        Medics.remove(index);
        modelo.remove(index);
    }

    public void Cargar(int index, Paciente paciente) {
        Consultas.Consulta consult = array.get(0).getConsultas().get(index);
        System.out.println(consult.toString());
        ShowDoctor.setText(consult.getDoctor().getNombre());
        ShowEspecialidad.setText(consult.getDoctor().getEspecialidad());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textField1 = new java.awt.TextField();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        Display_FechaConsulta = new javax.swing.JLabel();
        CrearConsultaButton = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        IngresarEnfermedad = new javax.swing.JButton();
        Display_Diagnostico = new javax.swing.JLabel();
        RecetaIngreso = new javax.swing.JTextField();
        IngMedi = new javax.swing.JButton();
        Display_Receta = new javax.swing.JLabel();
        Cronico = new javax.swing.JCheckBox();
        Display_Doctor = new javax.swing.JLabel();
        ShowDoctor = new javax.swing.JLabel();
        Display_Especialidad = new javax.swing.JLabel();
        ShowEspecialidad = new javax.swing.JLabel();
        Display_Paciente = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        Enfermedades = new javax.swing.JList<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        Receta = new javax.swing.JList<>();
        BorrarDiagnostic = new javax.swing.JButton();
        BorrarReceta = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        FechasList = new javax.swing.JList<>();
        IngresarEnfermedad1 = new javax.swing.JButton();

        textField1.setText("textField1");

        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1540, 960));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1540, 872));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        Display_FechaConsulta.setText("Fechas de Consulta");

        CrearConsultaButton.setBackground(new java.awt.Color(50, 119, 189));
        CrearConsultaButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        CrearConsultaButton.setForeground(new java.awt.Color(255, 255, 255));
        CrearConsultaButton.setText("Terminar Diagnostico");
        CrearConsultaButton.setBorderPainted(false);
        CrearConsultaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearConsultaButtonActionPerformed(evt);
            }
        });

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        IngresarEnfermedad.setBackground(new java.awt.Color(50, 119, 189));
        IngresarEnfermedad.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        IngresarEnfermedad.setForeground(new java.awt.Color(255, 255, 255));
        IngresarEnfermedad.setText("Ingresar");
        IngresarEnfermedad.setBorderPainted(false);
        IngresarEnfermedad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngresarEnfermedadActionPerformed(evt);
            }
        });

        Display_Diagnostico.setText("Diagnostico");

        RecetaIngreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RecetaIngresoActionPerformed(evt);
            }
        });

        IngMedi.setBackground(new java.awt.Color(50, 119, 189));
        IngMedi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        IngMedi.setForeground(new java.awt.Color(255, 255, 255));
        IngMedi.setText("Ingresar");
        IngMedi.setBorderPainted(false);
        IngMedi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngMediActionPerformed(evt);
            }
        });

        Display_Receta.setText("Receta");

        Cronico.setText("Crónico");
        Cronico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CronicoActionPerformed(evt);
            }
        });

        Display_Doctor.setText("Doctor:");

        ShowDoctor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Display_Especialidad.setText("Especialidad:");

        ShowEspecialidad.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Display_Paciente.setText("Paciente:");

        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Enfermedades.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(Enfermedades);

        Receta.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane4.setViewportView(Receta);

        BorrarDiagnostic.setBackground(new java.awt.Color(204, 0, 51));
        BorrarDiagnostic.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        BorrarDiagnostic.setForeground(new java.awt.Color(255, 255, 255));
        BorrarDiagnostic.setText("Borrar");
        BorrarDiagnostic.setBorderPainted(false);
        BorrarDiagnostic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BorrarDiagnosticActionPerformed(evt);
            }
        });

        BorrarReceta.setBackground(new java.awt.Color(204, 0, 51));
        BorrarReceta.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        BorrarReceta.setForeground(new java.awt.Color(255, 255, 255));
        BorrarReceta.setText("Borrar");
        BorrarReceta.setBorderPainted(false);
        BorrarReceta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BorrarRecetaActionPerformed(evt);
            }
        });

        FechasList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane5.setViewportView(FechasList);

        IngresarEnfermedad1.setBackground(new java.awt.Color(50, 119, 189));
        IngresarEnfermedad1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        IngresarEnfermedad1.setForeground(new java.awt.Color(255, 255, 255));
        IngresarEnfermedad1.setText("Buscar");
        IngresarEnfermedad1.setBorderPainted(false);
        IngresarEnfermedad1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngresarEnfermedad1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(287, 287, 287)
                                                .addComponent(CrearConsultaButton))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                                .addGroup(jPanel2Layout.createSequentialGroup()
                                                                                        .addComponent(Display_Diagnostico)
                                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                                        .addComponent(Cronico))
                                                                                .addGroup(jPanel2Layout.createSequentialGroup()
                                                                                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                        .addComponent(IngresarEnfermedad))
                                                                                .addComponent(Display_Doctor)
                                                                                .addComponent(ShowDoctor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                                        .addComponent(BorrarDiagnostic)
                                                                        .addComponent(Display_FechaConsulta)
                                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addComponent(IngresarEnfermedad1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                .addGap(56, 56, 56)
                                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                                                .addComponent(Display_Paciente)
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                                        .addComponent(BorrarReceta)
                                                                        .addComponent(Display_Especialidad)
                                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                                                .addComponent(RecetaIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addComponent(IngMedi))
                                                                        .addComponent(Display_Receta)
                                                                        .addComponent(ShowEspecialidad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                                .addContainerGap(894, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(Display_FechaConsulta)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(IngresarEnfermedad1)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(Display_Paciente)
                                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addComponent(Display_Diagnostico)
                                                                .addGap(10, 10, 10))
                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addComponent(Cronico)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(IngresarEnfermedad))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                                .addComponent(Display_Receta)
                                                .addGap(10, 10, 10)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(RecetaIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(IngMedi))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(5, 5, 5)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(BorrarDiagnostic)
                                        .addComponent(BorrarReceta))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(Display_Doctor)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(ShowDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(Display_Especialidad)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(ShowEspecialidad, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(41, 41, 41)
                                .addComponent(CrearConsultaButton)
                                .addContainerGap(434, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(890, 890, 890))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 206, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void CrearConsultaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearConsultaButtonActionPerformed
        // TODO add your handling code here:
        int index = FechasList.getSelectedIndex();

        Diagnostico diag = new Diagnostico(array.get(0).getConsultas().get(index).getFechaConsulta(), array.get(0).getConsultas().get(index).getDoctor());
        diag.setEnfermedades(Enfers);
        diag.setMedicamentos(Medics);

        Paciente paciente = array.get(0);

        Paciente temp;

        String t = array.get(0).toString();

        try {
            temp = FileManager.deserialized(t);
            temp.getHistorialMedico().insert(diag.getId(), diag);

            FileManager.actualizarPaciente("paciente.txt", paciente.toString(), temp.toString());
        } catch (ParseException ex) {
            Logger.getLogger(FormularioDiagnostico.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_CrearConsultaButtonActionPerformed

    private void IngresarEnfermedadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngresarEnfermedadActionPerformed
        // TODO add your handling code here:
        Enfermedad string = new Enfermedad(jTextField1.getText(), Cronico.isSelected());
        EnferAgregarAct(string, Enferme);
        Enfermedades.setModel(Enferme);
    }//GEN-LAST:event_IngresarEnfermedadActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void RecetaIngresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RecetaIngresoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RecetaIngresoActionPerformed

    private void IngMediActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngMediActionPerformed
        // TODO add your handling code here:
        String string = RecetaIngreso.getText();
        MedAgregarAct(string, Medic);
        Receta.setModel(Medic);
    }//GEN-LAST:event_IngMediActionPerformed

    private void CronicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CronicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CronicoActionPerformed

    private void BorrarDiagnosticActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BorrarDiagnosticActionPerformed
        // TODO add your handling code here:
        int index = Enfermedades.getSelectedIndex();
        EnferEliminarAct(index, Enferme);
        Enfermedades.setModel(Enferme);
    }//GEN-LAST:event_BorrarDiagnosticActionPerformed

    private void BorrarRecetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BorrarRecetaActionPerformed
        // TODO add your handling code here:
        int index = Receta.getSelectedIndex();
        MedEliminarAct(index, Medic);
        Receta.setModel(Medic);
    }//GEN-LAST:event_BorrarRecetaActionPerformed

    private void IngresarEnfermedad1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngresarEnfermedad1ActionPerformed
        // TODO add your handling code here:
        int index = FechasList.getSelectedIndex();
        Cargar(index, array.get(0));
    }//GEN-LAST:event_IngresarEnfermedad1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BorrarDiagnostic;
    private javax.swing.JButton BorrarReceta;
    private javax.swing.JButton CrearConsultaButton;
    private javax.swing.JCheckBox Cronico;
    private javax.swing.JLabel Display_Diagnostico;
    private javax.swing.JLabel Display_Doctor;
    private javax.swing.JLabel Display_Especialidad;
    private javax.swing.JLabel Display_FechaConsulta;
    private javax.swing.JLabel Display_Paciente;
    private javax.swing.JLabel Display_Receta;
    private javax.swing.JList<String> Enfermedades;
    private javax.swing.JList<String> FechasList;
    private javax.swing.JButton IngMedi;
    private javax.swing.JButton IngresarEnfermedad;
    private javax.swing.JButton IngresarEnfermedad1;
    private javax.swing.JList<String> Receta;
    private javax.swing.JTextField RecetaIngreso;
    private javax.swing.JLabel ShowDoctor;
    private javax.swing.JLabel ShowEspecialidad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextField jTextField1;
    private java.awt.TextField textField1;
    // End of variables declaration//GEN-END:variables
}
