/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package main.views;

import main.*;
import Pacientes.*;
import Consultas.*;

import java.text.SimpleDateFormat;
import java.util.Date;
import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import static main.SistemaSalud.guardarPacienteEnArchivo;

/**
 *
 * @author PC
 */


public class Ingresar_paciente extends javax.swing.JPanel {

    private HashA<Paciente> pacientes;

    public Ingresar_paciente() {
        initComponents();
        pacientes = new HashA<>(100);
        InitStyles();
    }

    private void InitStyles(){
        Color colorBase = new Color(50,119,189);
        Display_Alergias.putClientProperty("Flatlaf.styleClass","default");
        Display_Alergias.setForeground(Color.black);
        Display_AntFam.putClientProperty("Flatlaf.styleClass","default");
        Display_AntFam.setForeground(Color.black);
        Display_ApellidoM.putClientProperty("Flatlaf.styleClass","default");
        Display_ApellidoM.setForeground(Color.black);
        Display_ApellidoP.putClientProperty("Flatlaf.styleClass","default");
        Display_ApellidoP.setForeground(Color.black);
        Display_DNI.putClientProperty("Flatlaf.styleClass","default");
        Display_DNI.setForeground(Color.black);
        Display_EnfermedadesPre.putClientProperty("Flatlaf.styleClass","default");
        Display_EnfermedadesPre.setForeground(Color.black);
        Display_FechaNacimiento.putClientProperty("Flatlaf.styleClass","default");
        Display_FechaNacimiento.setForeground(Color.black);
        Display_MedicamentosAct.putClientProperty("Flatlaf.styleClass","default");
        Display_MedicamentosAct.setForeground(Color.black);
        Display_Nombre.putClientProperty("Flatlaf.styleClass","default");
        Display_Nombre.setForeground(Color.black);
        Display_OperacionesPrevias.putClientProperty("Flatlaf.styleClass","default");
        Display_OperacionesPrevias.setForeground(Color.black);
        Title1.putClientProperty("Flatlaf.style","font: semibold $h2.regular.font");
        Title1.setForeground(colorBase);
        Title2.putClientProperty("Flatlaf.style","font: semibold $h2.regular.font");
        Title2.setForeground(colorBase);
        jLabel14.putClientProperty("Flatlaf.styleClass","default");
        jLabel14.setForeground(Color.black);
        jLabel15.putClientProperty("Flatlaf.styleClass","default");
        jLabel15.setForeground(Color.black);
        subTitle1.putClientProperty("Flatlaf.styleClass","default");
        subTitle1.setForeground(Color.black);
        subTitle2.putClientProperty("Flatlaf.styleClass","default");
        subTitle2.setForeground(Color.black);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")



    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textField1 = new java.awt.TextField();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        IngresarNombre = new javax.swing.JTextField();
        IngresarPaterno = new javax.swing.JTextField();
        Display_Nombre = new javax.swing.JLabel();
        Display_ApellidoP = new javax.swing.JLabel();
        Display_ApellidoM = new javax.swing.JLabel();
        Display_DNI = new javax.swing.JLabel();
        IngresarDNI = new javax.swing.JTextField();
        IngresarMaterno = new javax.swing.JTextField();
        Display_FechaNacimiento = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        Title2 = new javax.swing.JLabel();
        Display_EnfermedadesPre = new javax.swing.JLabel();
        IngresarMediActual = new javax.swing.JTextField();
        Display_MedicamentosAct = new javax.swing.JLabel();
        IngresarAntece = new javax.swing.JTextField();
        Display_OperacionesPrevias = new javax.swing.JLabel();
        IngresarOpPrevias = new javax.swing.JTextField();
        Display_AntFam = new javax.swing.JLabel();
        IngresarEnferPre = new javax.swing.JTextField();
        Display_Alergias = new javax.swing.JLabel();
        IngresarAlergia = new javax.swing.JTextField();
        Title1 = new javax.swing.JLabel();
        IngresarAnio = new javax.swing.JTextField();
        subTitle1 = new javax.swing.JLabel();
        IngresarDia = new javax.swing.JTextField();
        IngresarMes = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        subTitle2 = new javax.swing.JLabel();

        textField1.setText("textField1");

        setForeground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1540, 960));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setToolTipText("");
        jPanel1.setPreferredSize(new java.awt.Dimension(1540, 960));

        jButton1.setBackground(new java.awt.Color(50, 119, 189));
        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Registrarse");
        jButton1.setBorderPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        IngresarNombre.setForeground(new java.awt.Color(255, 255, 255));
        IngresarNombre.setCaretColor(new java.awt.Color(50, 119, 189));
        IngresarNombre.setDisabledTextColor(new java.awt.Color(50, 119, 189));
        IngresarNombre.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        IngresarNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngresarNombreActionPerformed(evt);
            }
        });

        IngresarPaterno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngresarPaternoActionPerformed(evt);
            }
        });

        Display_Nombre.setText("Nombre:");

        Display_ApellidoP.setText("Apellido Paterno:");

        Display_ApellidoM.setText("Apellido Materno:");

        Display_DNI.setText("DNI:");

        IngresarDNI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngresarDNIActionPerformed(evt);
            }
        });

        IngresarMaterno.setSelectionColor(new java.awt.Color(50, 119, 189));
        IngresarMaterno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngresarMaternoActionPerformed(evt);
            }
        });

        Display_FechaNacimiento.setText("Fecha de Nacimiento:");

        jSeparator3.setBackground(new java.awt.Color(50, 119, 189));
        jSeparator3.setForeground(new java.awt.Color(50, 119, 189));

        Title2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        Title2.setForeground(new java.awt.Color(50, 119, 189));
        Title2.setText("Antecedentes:");

        Display_EnfermedadesPre.setText("Enfermedades Preexistentes (Crónicos):");

        IngresarMediActual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngresarMediActualActionPerformed(evt);
            }
        });

        Display_MedicamentosAct.setText("Medicamentos Actuales:");

        IngresarAntece.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngresarAnteceActionPerformed(evt);
            }
        });

        Display_OperacionesPrevias.setText("Operaciones Previas:");

        IngresarOpPrevias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngresarOpPreviasActionPerformed(evt);
            }
        });

        Display_AntFam.setText("Antecedentes Familiares:");

        IngresarEnferPre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngresarEnferPreActionPerformed(evt);
            }
        });

        Display_Alergias.setText("Alergias:");

        IngresarAlergia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngresarAlergiaActionPerformed(evt);
            }
        });

        Title1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        Title1.setForeground(new java.awt.Color(50, 119, 189));
        Title1.setText("Datos Personales:");

        IngresarAnio.setText("YYYY");
        IngresarAnio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngresarAnioActionPerformed(evt);
            }
        });

        subTitle1.setText("(Si tiene varios, dividalos por comas ',' )");

        IngresarDia.setText("DD");
        IngresarDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngresarDiaActionPerformed(evt);
            }
        });

        IngresarMes.setText("MM");
        IngresarMes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngresarMesActionPerformed(evt);
            }
        });

        jLabel14.setText("/");

        jLabel15.setText("/");

        subTitle2.setText("(en caso de no contar con alguno, déjelo vacío)");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(61, 61, 61)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(subTitle2)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 678, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(Title2)
                                                .addComponent(subTitle1)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addComponent(Display_MedicamentosAct)
                                                        .addGap(232, 232, 232)
                                                        .addComponent(Display_Alergias))
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addComponent(IngresarMediActual, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(42, 42, 42)
                                                        .addComponent(IngresarAlergia, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addComponent(Display_OperacionesPrevias)
                                                .addComponent(IngresarOpPrevias, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(Title1)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addComponent(Display_Nombre)
                                                        .addGap(315, 315, 315)
                                                        .addComponent(Display_DNI))
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addComponent(IngresarNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(42, 42, 42)
                                                        .addComponent(IngresarDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addComponent(Display_ApellidoP)
                                                                .addComponent(Display_ApellidoM)
                                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(IngresarPaterno, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(IngresarMaterno, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                        .addGap(42, 42, 42)
                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addComponent(Display_FechaNacimiento)
                                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                                        .addComponent(IngresarDia, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                        .addComponent(jLabel14)
                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                        .addComponent(IngresarMes, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                        .addComponent(jLabel15)
                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                        .addComponent(IngresarAnio, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                .addComponent(Display_EnfermedadesPre, javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addComponent(IngresarEnferPre, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGap(42, 42, 42)
                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addComponent(IngresarAntece, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(Display_AntFam)))))
                                .addContainerGap(797, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(Title1)
                                .addGap(6, 6, 6)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(Display_Nombre)
                                        .addComponent(Display_DNI))
                                .addGap(6, 6, 6)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(IngresarNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(IngresarDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(6, 6, 6)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(Display_ApellidoP)
                                        .addComponent(Display_FechaNacimiento))
                                .addGap(12, 12, 12)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(IngresarPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jLabel14)
                                                .addComponent(IngresarDia, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel15)
                                                .addComponent(IngresarMes, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(IngresarAnio, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(6, 6, 6)
                                .addComponent(Display_ApellidoM)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(IngresarMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(Title2)
                                .addGap(6, 6, 6)
                                .addComponent(subTitle1)
                                .addGap(10, 10, 10)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(Display_EnfermedadesPre)
                                        .addComponent(Display_AntFam))
                                .addGap(6, 6, 6)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(IngresarEnferPre, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(IngresarAntece, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(6, 6, 6)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(Display_MedicamentosAct)
                                        .addComponent(Display_Alergias))
                                .addGap(6, 6, 6)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(IngresarMediActual, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(IngresarAlergia, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(6, 6, 6)
                                .addComponent(Display_OperacionesPrevias)
                                .addGap(6, 6, 6)
                                .addComponent(IngresarOpPrevias, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(subTitle2)
                                .addGap(31, 31, 31)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(378, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {

            if(IngresarDNI.getText().trim().length()!=8){
                throw new Exception("DNI Inválido.");
            }
            String nombre = IngresarNombre.getText().trim() + " " + IngresarPaterno.getText().trim() + " " + IngresarMaterno.getText().trim();
            String dni = IngresarDNI.getText().trim();
            String dia = IngresarDia.getText().trim();
            String mes = IngresarMes.getText().trim();
            String anio = IngresarAnio.getText().trim();
            String fechaNacimientoStr = anio + "-" + mes + "-" + dia;
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            Date fechaNacimiento = sdf.parse(fechaNacimientoStr);
            System.out.println(fechaNacimiento);
            List<String> alergia = FileManager.generateListFromCommaSeparatedString(IngresarAlergia.getText().trim());
            List<String> enfermedadPrevia = FileManager.generateListFromCommaSeparatedString(IngresarEnferPre.getText().trim());
            List<String> operacionPrevia = FileManager.generateListFromCommaSeparatedString(IngresarOpPrevias.getText().trim());
            List<String> antecedente = FileManager.generateListFromCommaSeparatedString(IngresarAntece.getText().trim());
            List<String> medicamentoActual = FileManager.generateListFromCommaSeparatedString(IngresarMediActual.getText().trim());

            InfoPaciente ip = new InfoPaciente();
            if (!enfermedadPrevia.isEmpty()) {
                for(String s : enfermedadPrevia){
                    ip.agregarEnfermedadPreexistente(new Enfermedad(s, true));
                }
            }
            if (!medicamentoActual.isEmpty()) {
                ArrayList<String> medications = new ArrayList<>();
                medications.addAll(medicamentoActual);
                ip.setMedicacion(medications);
            }
            if (!operacionPrevia.isEmpty()) {
                ArrayList<String> ops = new ArrayList<>();
                ops.addAll(operacionPrevia);
                ip.setOperaciones(ops);
            }
            if (!antecedente.isEmpty()) {
                ArrayList<String> antecs = new ArrayList<>();
                antecs.addAll(antecedente);
                ip.setAntecedentesFamiliares(antecs);
            }
            if (!alergia.isEmpty()) {
                ArrayList<String> alergies = new ArrayList<>();
                alergies.addAll(alergia);
                ip.setAlergias(alergies);
            }


            Paciente paciente = new Paciente(nombre, dni, fechaNacimiento);
            paciente.setInfoPersonal(ip);

            pacientes.insert(Integer.parseInt(paciente.getDNI()), paciente);

            guardarPacienteEnArchivo(paciente);

            System.out.println("Paciente creado correctamente: " + paciente);
            System.out.println(pacientes.getAllElements());
            JOptionPane.showMessageDialog(this, "Paciente creado correctamente", "Éxito", JOptionPane.INFORMATION_MESSAGE);
            // Aquí limpias los campos de texto

            IngresarNombre.setText("");
            IngresarPaterno.setText("");
            IngresarMaterno.setText("");
            IngresarDNI.setText("");
            IngresarDia.setText("");
            IngresarMes.setText("");
            IngresarAnio.setText("");
            IngresarAlergia.setText("");
            IngresarEnferPre.setText("");
            IngresarOpPrevias.setText("");
            IngresarAntece.setText("");
            IngresarMediActual.setText("");


        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al crear el paciente: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            System.out.println("Error al crear el paciente: " + e.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void IngresarMediActualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngresarMediActualActionPerformed

    }//GEN-LAST:event_IngresarMediActualActionPerformed

    private void IngresarAnteceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngresarAnteceActionPerformed

    }//GEN-LAST:event_IngresarAnteceActionPerformed

    private void IngresarOpPreviasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngresarOpPreviasActionPerformed

    }//GEN-LAST:event_IngresarOpPreviasActionPerformed

    private void IngresarEnferPreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngresarEnferPreActionPerformed

    }//GEN-LAST:event_IngresarEnferPreActionPerformed

    private void IngresarAlergiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngresarAlergiaActionPerformed

    }//GEN-LAST:event_IngresarAlergiaActionPerformed

    private void IngresarAnioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngresarAnioActionPerformed

    }//GEN-LAST:event_IngresarAnioActionPerformed

    private void IngresarDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngresarDiaActionPerformed

    }//GEN-LAST:event_IngresarDiaActionPerformed

    private void IngresarMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngresarMesActionPerformed

    }//GEN-LAST:event_IngresarMesActionPerformed

    private void IngresarMaternoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngresarMaternoActionPerformed

    }//GEN-LAST:event_IngresarMaternoActionPerformed

    private void IngresarPaternoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngresarPaternoActionPerformed

    }//GEN-LAST:event_IngresarPaternoActionPerformed

    private void IngresarDNIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngresarDNIActionPerformed

    }//GEN-LAST:event_IngresarDNIActionPerformed

    private void IngresarNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngresarNombreActionPerformed

    }//GEN-LAST:event_IngresarNombreActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Display_Alergias;
    private javax.swing.JLabel Display_AntFam;
    private javax.swing.JLabel Display_ApellidoM;
    private javax.swing.JLabel Display_ApellidoP;
    private javax.swing.JLabel Display_DNI;
    private javax.swing.JLabel Display_EnfermedadesPre;
    private javax.swing.JLabel Display_FechaNacimiento;
    private javax.swing.JLabel Display_MedicamentosAct;
    private javax.swing.JLabel Display_Nombre;
    private javax.swing.JLabel Display_OperacionesPrevias;
    private javax.swing.JTextField IngresarAlergia;
    private javax.swing.JTextField IngresarAnio;
    private javax.swing.JTextField IngresarAntece;
    private javax.swing.JTextField IngresarDNI;
    private javax.swing.JTextField IngresarDia;
    private javax.swing.JTextField IngresarEnferPre;
    private javax.swing.JTextField IngresarMaterno;
    private javax.swing.JTextField IngresarMediActual;
    private javax.swing.JTextField IngresarMes;
    private javax.swing.JTextField IngresarNombre;
    private javax.swing.JTextField IngresarOpPrevias;
    private javax.swing.JTextField IngresarPaterno;
    private javax.swing.JLabel Title1;
    private javax.swing.JLabel Title2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel subTitle1;
    private javax.swing.JLabel subTitle2;
    private java.awt.TextField textField1;
    // End of variables declaration//GEN-END:variables
}